language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - "11"
  - "10"
stages:
  - test
  - build
  - audit
  - name: release
    if: branch = master
jobs:
  include:
    - stage: test
      name: "Tests"
      script: npm run test
    - stage: build
      name: "Build"
      script: npm run build
    - stage: audit
      name: "Audit"
      script: npm audit --only=prod --audit-level=critical
    - stage: release
      name: "Release"
      script: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
